# Generated by Django 5.1.2 on 2024-12-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_product_price'),
        ('UserApp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('usercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.register')),
                ('userpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.product')),
            ],
        ),
    ]
