# Generated by Django 5.1.2 on 2024-12-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='city',
            new_name='state',
        ),
    ]
